import { Poppins } from "next/font/google";
import PathAwareSidebar from './components/PathAwareSidebar.jsx';
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Chess Champs 2.0",
  description: "Generated by Chess Champs 2.0",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <div style={{ display: "flex" }}>
          <PathAwareSidebar />
          <main style={{ width: "100%", padding: "1rem" }}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
